# Generated by Django 3.2.7 on 2021-10-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('image1', models.ImageField(upload_to='productitem/%m/%d/')),
                ('image2', models.ImageField(upload_to='productitem/%m/%d/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
            ],
        ),
    ]
