# Generated by Django 3.2.7 on 2021-11-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_otpemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPemail',
        ),
    ]
