# Generated by Django 3.2.7 on 2021-11-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_otpemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPemail',
            new_name='Emailotp',
        ),
    ]
