# Generated by Django 3.2.7 on 2021-11-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_productitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='placedorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productitem')),
            ],
        ),
    ]
