# Generated by Django 3.2.7 on 2021-11-09 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_otpemail_emailotp'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentotp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcode', models.CharField(max_length=10)),
                ('time_stp', models.DateTimeField(default=django.utils.timezone.now)),
                ('otp', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
            ],
        ),
    ]
